
name: Netlify workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    
    

jobs:
  updateBlogs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 

      - name: execute script
        run: |
          node public/main.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update blogs file [skip ci]"
          git push

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i

      - run: npm run build --if-present

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0

      - name: Netlify Deploy

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod
