
name: Netlify workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    
    

jobs:
  updateBlogs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 

      - name: execute script
        run: |
          node public/main.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          set +e 
          git status | grep modified
          if [ $? -eq 0 ]
          then
              set -e
              git commit -am "updated on - $(date) [skip ci]"
              git push
          else
              set -e
              echo "No changes since last run"
          fi
          

      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
